theme: jekyll-theme-minimal
title: Easy ADB and fastboot (EAF)
description: a GUI tool for easier using ADB and fastboot
show_downloads: true
github: 
  zip_url: https://github.com/ryantsui1109/Easy_ADB_fastboot/releases/latest/download/Easy-ADB-and-fastboot-win-x64.exe
  tar_url: https://github.com/ryantsui1109/Easy_ADB_fastboot/releases/latest/download/Easy-ADB-and-fastboot-linux-x64.tar.xz
  repository_url: https://github.com/ryantsui1109/Easy_ADB_fastboot
  repository_nwo: ryantsui1109/Easy_ADB_fastboot
